### ISSUE TITLE
Scene numbers in night mode are barely visible

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#1]
Switch to night mode. Scene numbers are black on dark grey; hard to see.

![big_fish__john_august___final___digital__fountain](https://user-images.githubusercontent.com/3142193/53642487-e703dc80-3bff-11e9-8bc3-14cde4122c4e.png)

**Comment by lmparppei** [comment]
Thanks. The issue was that updateSceneNumberLabels didn't fetch the current text color.

`[label setTextColor:self.themeManager.currentTextColor];`
