### ISSUE TITLE
API suggestion: Beat.sendKeyPressToBeat() 

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#100]
Okay, so that may be an ugly name. But you get the idea.

So -- not sure that anyone in the world has really found my plugin yet -- but I'll pretend as if until proven otherwise. (And since I'm using it all the time, I'll call this a user request...) :grin:

Working with multiple episodes (which now works *wonderfully*, with Beat shifting plugin windows as I switch between tabs) there is one thing that stops me in my tracks from time to time -- which is, not being able to press `ctrl + tab` to shift tabs when the plugin is focused.

For that reason, it would be great if I could programmatically choose to send certain key combinations to the main window -- like, in my case:
``` javascript
if (e.key == "Tab" && e.ctrlKey){Beat.call("Beat.sendKeyPressToBeat(" + e + ")")}
```
(or perhaps I need to spread the `e` when sending it to the plugin? Hm. Anyway, hope you see what I mean in spite of my lacking coding skills...)

So -- while ctrl+Tab is what I'm missing personally, I'm sure there are other commands that someone would like to reach when a plugin is focused, hence the suggestion.

Hope this makes sense!

**Comment by lmparppei** [comment]
As far as I know, this is disallowed because of security reasons (the app can't just send key commands anywhere without the user knowing it). However, I can add something like `Beat.nextTab()` and `Beat.previousTab()`.

**Comment by ftolsson** [comment]
Aha! Makes sense! 

I would totally love a `.nextTab()`/`.previousTab()` command, so much obliged!

(Question: As of currently, *some* keypresses are already passed through to the main app, such as (at least) `cmd+z` and `shift+cmd+z`. Is this something you have control over? Because if so, perhaps an even easier way is to always allow passthrough for `ctrl+tab` and `shit+ctrl+tab` as well?)

Anyways, would be a great addition!

**Comment by lmparppei** [comment]
> (Question: As of currently, _some_ keypresses are already passed through to the main app, such as (at least) `cmd+z` and `shift+cmd+z`. Is this something you have control over? Because if so, perhaps an even easier way is to always allow passthrough for `ctrl+tab` and `shift+ctrl+tab` as well?)

I'm not actually quite sure. I think it's mostly keypresses that aren't currently attached to any methods — and, as any window could have tabs, when pressed inside the HTML window, nothing happens. I'll see if I can pass them through.

**Comment by ftolsson** [comment]
That is a very good point. And it could very well be that someone someday writes a tab-based plugin, and wants `ctrl+tab` for themselves.

For that reason, perhaps your idea of `Beat.nextTab()` (which a coder could bind to whatever they please) is in fact the best solution after all!

**Comment by lmparppei** [comment]
Some changes with this in `1.92.9`:  
- HTML Windows have their tabbing mode set to `disallowed`
- API now has `Beat.nextTab()` and `Beat.previousTab()` methods for navigating between tabs

I haven't had the time to test out how these affect tabbing or keypresses inside windows, so I'm providing a dev build tomorrow on Discord.
