### ISSUE TITLE
Small glitch: Exporting to FDX adds one character from [[color note]] to slugline (if locked numbers present)

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#102]
I think the subject line says it — exporting a scene heading with a locked number and a color, like 

`INT. SOMEWHERE -- DAY #104# [[COLOR BLUE]]`

will add one letter from a couple of characters into the note (exact position on the length of the locked scene number string) and add it to the end of the slugline.

So the above will appear in Final Draft as

`INT. SOMEWHERE -- DAY O`

Another one not to lose sleep over (but also, I predict, probably not too hard to fix).

**Comment by lmparppei** [comment]
This happens only in FDX, not in PDF?

**Comment by ftolsson** [comment]
Yep. FDX only.

**Comment by lmparppei** [comment]
Ah, old code lingering around. Fixed in `1.92.9`
