### ISSUE TITLE
Suggestion: Add different number of asterisks to different revision generations

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#104]
Having peeked quite far into the print CSS, I dint *think* this is doable yet.
But I do think it would probably not be too hard to achieve:

Currently, there is only one `.changed::after` class in the css, adding a star to changed elements.

But since I can select four different revision colors (which do get exported to Final Draft, so the text itself is no doubt aware what revision color it is) could we not expand that into:

```
.changed.blue::after{
content"************************";
width: 8px;
}

.changed.orange::after{
content"************************";
width: 16px;
}

.changed.purple::after{
content"************************";
width: 24px;
}

//...etc 
```

...so that different revision generations would get different amount of stars? This would of course be invaluable when making new changes to already-revised and delivered text. 

(I tried to change this directly in the CSS to try it out myself, but it seems that revised text are not exported for print with an extra class right now -- at least not named `.orange`
Do you already assign different classes to different generations, and if so what do you call them? Would love to experiment with the above.)

**Comment by lmparppei** [comment]
It's doable, but requires some changes to the already convoluted export code.

To explain (also as a note to myself):

Revised ranges are saved as **ranges** and not inside the actual lines. When Beat sends the screenplay to be printed / exported, it "bakes" the changes into lines, so, for example:

```
The **bolded** range here is revised.
```

In editor, the bolded section has a *text attribute* with `BeatRevisionItem`, which knows the color and nothing else, and can span over multiple lines etc.

So, before exporting, Beat takes in the WHOLE SCREENPLAY as plain text, parses it again, and then iterates through attributes that contain `BeatRevisionItem`. It checks if `Line` range is in `BeatRevisionItem` range, and for that line, sets `.changed` as `true`.

The only actual changes this would require is that we add a string property like `.revision` to `Line`. Then, at baking phase, just either set the `revision` attribute or both that and `changed`, and have `BeatHTMLScript` add the additional revision color class to elements.

**Comment by lmparppei** [comment]
Revisions now have a class name (`.changed.blue`, for example) in `1.929` beta 3, available on Discord.

**Comment by lmparppei** [comment]
Revisions have now been renamed:

Blue = First
Orange = Second
Purple = Third
Green = Fourth

CSS classes:
First: `.blue`  
Second: `.orange`  
Third: `.purple`  
Fourth: `.green` 

The original color names still linger around in both CSS and code, because otherwise, backwards-compatibility would be a bit tricky and time-consuming to achieve.

**Comment by lmparppei** [comment]
I also added the possibility to hide/show revisions. They are still be there, but won't be rendered.

**Comment by ftolsson** [comment]
Thumbs up to all of the above!

I spent yesterday evening running into the shrinking page phenomenon as soon as I touched the plist -- but five minutes ago I realized there was a solution that is both better, easier and also changes nothing but the position of stars.
For whatever reason, there was indeed some space to spare to the right of stars and before that magic, shrinkage-inducing margin. 

So I just moved stars 8pt to the right, and since they are positioned `right:` the grow left-ward and can now include double characters without a problem.

I'll be back shortly!

**Comment by ftolsson** [comment]
![Beat_multiple_stars](https://user-images.githubusercontent.com/25481285/151696002-c87462d6-74f2-4593-839e-5d2ceac06cf3.gif)

**Comment by lmparppei** [comment]
Wow, well played! And no shrinking happening?

**Comment by ftolsson** [comment]
So above: an animation showing nothing has changed more than positioning of stars. 
Arguably, this even makes for a better (less cramped) spacing even when only one star, so win-win if you ask me.

**Comment by ftolsson** [comment]
No shrinking!

**Comment by lmparppei** [comment]
Nice! Put in a pull request or send me the CSS, I'll put it in!

**Comment by ftolsson** [comment]
I'll go the coward route and send it to you lest I break something...

It'll be a PM on discord!

But also as a side note, with this formatting there is no need to hide right scene numbers on changed lines anymore: There is now room between the two, even with two characters (see screenshot). 
And since the right scene number has `position: absolute` that *should* be taken out of the flow and thus not affect any of the other positions we've achieved now, so the way I see it you could just disable whatever line you have that checks that.

<img width="986" alt="image" src="https://user-images.githubusercontent.com/25481285/151696501-0cd56e0f-cf84-4ceb-b6bc-b62c179a48cd.png">

**Comment by ftolsson** [comment]
I can't help myself. I'm going to close this. Yihaa!
