### ISSUE TITLE
Two small suggestions re: revisions

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#107]
Two small suggestions that would be helpful when working with revisions:

**1. Menu command and/or shortcut to jump to next revision.** 
I'm sure there are oodles of useful reasons, but for one, when making changes to an already translated script and in order to update that other document, not having to scroll and manually finding every revision would be very helpful

**2. Command to remove all revision marks**
This can already be done by selecting the entire script and choosing `clear selected markers` so this is more of a nice to have, but for me doing it that way takes almost a minute (I'm guessing that Beat loops through all lines and evaluates them one by one).
My uneducated assumption here would be that such a command could just remove all the entries from the object that holds the changed lines all at once? In a case such as where I am right now -- with scripts "going back to white" before being distributed to the team -- that would just avoid some spinning beach ball time. Again nothing essential, just nice-to-have.

**Comment by lmparppei** [comment]
New revision code is much more optimized and removing the markers will take about 0,2 seconds.

I'm kind of feeling that revisions will need their own drop-down menu, which would contain at least the following items:

- Mark Selected Area as Revised
- Mark Selected Line as Revised
- Clear Revision Markers from Selection
- Clear All Revision Markers
- Jump To Next Revision
- Jump To Previous Revision

**Comment by lmparppei** [comment]
... OR, alternatively, make the menu item say *Mark Current Line as Revised* / *Mark Selection as Revised* depending on if there is a selection.

**Comment by ftolsson** [comment]
That all totally sounds great!

I cast my vote for number two -- I would be great with an intelligent "expansion" of the selection if nothing is selected.

In fact (and I shouldn't drop this in an unrelated issue but yet I'm about to) that's a Microsoft Word-y behavior that would be nice if consistently applied -- if selecting `bold` or `italic` or `uppercase`  etc when the caret is inside a word but nothing is selected, then intelligently first select the word I'm in before performing the action.

But anyways, great work with revisions over all!

**Comment by ftolsson** [comment]
BTW, if its own menu, may I suggest moving all commands for locking, forcing and setting the start for scene numbers over there as well? 
Looks like Beat is about to become old enough to have its own menu with production-related commands! They grow up so fast! And those would reasonably belong to that category (while also making the format menu a bit easier to navigate). IMO, of course.

**Comment by ftolsson** [comment]
I actually think that's pretty much a business term, "a screenwriting app with production features" mening just what we're talking about. 

I do see your point -- _production_ really is driving out to a location with a sminki bussi and start putting up lights -- but on the other hand the features we're talking about aren't really in play until you are "in production" (or at least close to.)

**Comment by lmparppei** [comment]
One possibility would be to create a new menu called *Screenplay*, and put revisions, scene numbering and title page stuff under that.

**Comment by lmparppei** [comment]
As so:

![image](https://user-images.githubusercontent.com/20226704/153876318-1b1cb046-56f4-48af-b1ee-d0297b539068.png)

**Comment by ftolsson** [comment]
Not bad! 👍

**Comment by lmparppei** [comment]
This will remove a lot of clutter from the other menus too, which is nice. I'm committing to it now.

**Comment by lmparppei** [comment]
AND, as for the 2nd part:
There's already code for something called *Commit Changes* which removes all the ranges which have been marked for removal and clears revision markers.

**Comment by ftolsson** [comment]
You're ahead of me!

**Comment by lmparppei** [comment]
Implemented at the moment: 
- All of the visual stuff discussed earlier, both in editor and export
- Jump to next/previous revision (ctrl-cmd-up/down)

Work in progress:
- Committing revised stuff

**Comment by lmparppei** [comment]
Thanks, that's fixed now.

**Comment by lmparppei** [comment]
Committing is in place now, too, as well functioning undo steps for revision markers. I think it's safe to close this issue now. Let's open issues for upcoming bugs, I'm sure there are some.
