### ISSUE TITLE
Automatic switch to dark mode only changes font color

### ISSUE THREAD

**Issue by tobibac** [lmparppei/Beat#109]
Only a minor issue but on my 2021 MacBook Pro I have to manually toggle dark mode on and off again to get the background to change properly as well. I have it set to automatically change according to the system wide setting.

**Comment by lmparppei** [comment]
Do you mean that colors don't change when you toggle macOS system-wide dark mode? 

Which macOS version are you using?

**Comment by lmparppei** [comment]
Thank you, fixed in version 1.93.1, out next week!
