### ISSUE TITLE
Mostly cosmetic: Context menu repeating itself

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#110]
I have sort of intuitively stayed away from using the context menu because it always overwhelmed me. It wasn't until today that I realised why it does... 😁 

<img width="240" alt="image" src="https://user-images.githubusercontent.com/25481285/155155099-62487594-8a3c-4f06-9de8-533c945bc930.png">

(Outside of the obvious doubled stuff, are you sure you need the share sheet, and all the OS standard spelling/substitution submenus? Perhaps it's just me, but I have a feeling things that are three clicks deep won't be used too often anyway. I could be wrong of course, but if I'm not then a briefer context menu might be more inviting to use. My two cents, in case you agree.)

**Comment by lmparppei** [comment]
Wow, interestingly enough, the more documents you've opened, it multiplies all the time. There isn't a sensible reason for this, I'll have to fix it ASAP.

**Comment by lmparppei** [comment]
Fixed in `1.932`. I'll try to remove the unnecessary items as well.
