### ISSUE TITLE
Bug: Issue when exporting to Final Draft with omitted lines 

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#111]
An observation:

Exporting the following text to FDX

```
INT. A PLACE

This is a first line
/*this is an adjacent omitted line*/
This line is number three and super important.
```

will only appear in Final Draft as 

```
INT. A PLACE

This is a first line
```

It seems quite consistently to be the case that if an omission end does NOT have a blank line before next, the following line will not export to FDX.

(Interestingly, if leaving out the scene heading, no lines appear in Final Draft at all. If this is due to the export, or if Final Draft can't interpret text outside of scene, I'm less sure of.)

**Comment by lmparppei** [comment]
Fixed in `1.932`
