### ISSUE TITLE
Bug: Final Draft Export issue: Blank lines disappear

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#112]
Oh yes, there are other things to worry about in the world right now. But if you should find a moment, exporting to Final Draft now seems to skip blank lines entirely. So nicely divided small chunks of action now end up as large blocks until next scene begins...

Also: Is there a way for me to find and download the previous App Store version, just so I can momentarily work around this without sacrificing the way Beat currently export changes/revisions/colors?

**Comment by lmparppei** [comment]
Fixed in `1.93.2`. No way to download older versions, but I'll push this fix later today and can provide you a dev build.
