### ISSUE TITLE
Low priority: Change to avoid import bug in Final Draft

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#113]
Nothing urgent, but here's an observation-turned-suggestion shared to keep my thoughts off of bigger things.

#### TL,DR;
Suggestion: Remove the `Style=""` tag that is currently added into revised (and only revised, it seems) lines when exporting to FDX.

#### THE REST
When exporting to PDF, Beat exports scene headings as they were typed -- i.e. without converting to uppercase -- which is reasonable. Final Draft's default scene heading font format dictates that they be displayed as uppercase, so that should be sorted out when displayed after import.
However, Final Draft seems to have a bug that excludes scene headings from being uppercased under certain circumstances:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/25481285/156723876-acadfb51-1f00-443c-a71f-bda2818518c3.png">

Looking into the FDX file exported by Beat, revised elements are exported with an empty `Style=""` tag:

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/25481285/156724963-9b6268ac-9f12-4bcd-b915-c31def9952ac.png">

Removing that tag will make Final Draft properly convert the scene heading to uppercase again.

#### TWO RELATED OBSERVATIONS:
* This seems to hold true to all element types that should be uppercased by Final Draft, most notably `transitions` (but perhaps other things too). So the `Style` tag should probably avoided as much as possible.
* Interestingly, even adding a valid value such as `Style="Italic"` which works fine for other element types, will cause FD to display the scene heading un-uppercased -- and even non-italicized, too. So it seems Final Draft simply has a bug in handling that tag, at least for elements set to uppercase.

**Comment by lmparppei** [comment]
This is now fixed in `1.92.4`.

> When exporting to PDF, Beat exports scene headings as they were typed -- i.e. without converting to uppercase -- which is reasonable. 

Did you confuse PDF/FDX here?

**Comment by ftolsson** [comment]
Totally. All three letter abbreviations look the same to me. That's what makes me an excellent coder.
