### ISSUE TITLE
Bug: Sidebar outline text doesn't wrap

### ISSUE THREAD

**Issue by crashmoney** [lmparppei/Beat#116]
**Describe the bug**

Text in the sidebar outline doesn't wrap, instead cutting off after a certain point (depending on the width of the sidebar). This makes it hard to read through screenplays with long synopses or scene headers.

**Suggested solution**

Wrap text in the sidebar outline (including section headers, scene headers and synopses) similar to the Review Notes tab.

**Comment by lmparppei** [comment]
This is a long-running issue which should finally be fixed. I personally like having compact lines, but the outline should have the option to show wrapping labels.
