### ISSUE TITLE
Feature suggestion: Using TAB for autocompletion in certain circumstances

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#119]
This is still being edited. Stupid Github for posting it already.

**Comment by ftolsson** [comment]
Should I finish this post? Maybe I should! 

Love the changes you made when I posted this the first time! Here are the remaining suggestions for a rainy day (or when you get stuck coding the new renderer... :)

- currently, tab jumps to character position only if preceded by empty line. When directly after other text, tab seemingly does nothing. **SUGGESTION:** When hitting TAB *anywhere*, add appropriate blank stuff (`cr + blank line` if at end of text line, `blank line` only if on empty line following text) and then put caret in character position. Reason: This would arguably closely mimic tab+enter based apps (like Final Draft) and simplify migration to Beat, but without changing any of Beat's functionality for those already used to Fountain.

- **SUGGESTED EXCEPTION** to above: When at the end of a character name, instead make TAB add `[space] + opening and closing parentheisis` after said name, putting caret between parenthesis for me to add extension such as `V.O.` or `O.S.` or even `CONT'D` etc.

- (Bonus points for then immediately opening drop down list of `V.O.`, `O.S.`, `CONT'D` or other previously used extensions -- and really, really bonus points for then stripping out extensions of character dropdown lists -- would you not agree that the character list would be cleaner if it only contained the characters, without extensions?)

That's about it. For your consideration, as they say.

**Comment by lmparppei** [comment]
This tab behavior is now implemented, save for the drop down for extensions.

**Comment by ftolsson** [comment]
You. Seriously. Rock.
