### ISSUE TITLE
parser.lineAtIndex() API method sometimes erroneously returns null value

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#121]
Not to yank you out of your holiday mode, but I just discovered that `Beat.currentParser.lineAtIndex(someLine)` doesn't behave the same as in previous versions:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/25481285/180767671-456135aa-409e-40eb-b4e2-7f3b8a65236c.png">

My latest version of FTOutliner works nice in the previous build but not in the App Store version -- have you made intentional changes to `.lineAtIndex`, or might there be something else happening?

Will keep researching to see if I can come up with more details about what Beat is protesting against.

**Comment by ftolsson** [comment]
CORRECTION. 

I should read error messages better. 

It seems that the object provided by `.lineAtIndex` does not contain a `string` key anymore, which it used to do previously.

Could I be right about that?

**Comment by lmparppei** [comment]
Whoops, I may have deprecated it by mistake in favor of `parser.lines[index]`. I'll pull the current patch and add it back.

**Comment by ftolsson** [comment]
`lineAtIndex(someIndex)` for a valid value of `index` seems to be producing nothing.

But it doesn't say that `lineAtIndex` is itself illegal, so I'm confused.

**Comment by ftolsson** [comment]
And forgive stupid Swede for saying `(someLine)` in the example code above, it should obviously be `(someIndex)`

**Comment by lmparppei** [comment]
This is probably related to my custom array item/index lookup. Here's some background:

To save some CPU time, Beat optimizes finding the needle in the haystack. Traditionally, when finding something in an array, it will be iterated from the beginning, and if this happens all the time, it will be surprisingly heavy on the CPU, especially with thousands of items.

When you are asking for a line at a position, Beat first checks if it's the same line that was requested previously. If it's not, the lookup begins from that specific line, and based on if the position is less or greater than the range of the line, array is iterated circularly either forwards or backwards. Sometimes we'll end up iterating through the whole array, but usually the match is nearby the latest position.

 I have a feeling there are some issues in the array search code, so that in some cases, it quits the iteration too early and returns `nil` (or `null` when speaking in JS API terms). I'll have to investigate further.

**Comment by ftolsson** [comment]
Question: Might deleting a chunk of text (spanning more than one line IRIC) confuse the index lookup?

I do remember doing just that moments before the first time I saw the error, and also -- by your description "starts at the line it previously requested", might there be a missing fallback for when that previously requested line is no more?

Haven't experienced it again so it's not quite that easily reproduced, but... yeah. Just a thought!

**Comment by lmparppei** [comment]
Hmmmm, it could be, especially if you are doing this in the background.

**Comment by ftolsson** [comment]
In fact, this happens on every text change in order to avoid running the text change code if the outline changed too:

```
Beat.onTextChange(function (location, length) { 

	if(location){

		let outlineDetector = Beat.currentParser.lineAtIndex(location)

		if (outlineDetector?.typeAsString() == "Section" 
			|| outlineDetector?.typeAsString() == "Heading" 
			|| outlineDetector?.typeAsString() == "Synopse"){

			return
		}
	}
```

Suggestions for clever-er ways to do this are welcome, but that's what I'm doing.

I now realize a couple of things: 
The fact that I worked for quite a while without an error means something specific triggered it, because every keypress should in fact lead here. 
I *think* the first error came right after deleting some text. 
But I'm also fairly certain that I did some editing after the deletion, but that shouldn't really be doable if .lineAtIndex had collapsed. 

Question: Did you change anything to the index lookup lately? Because if not, it feels odd that this should happen now when it hasn't before...

**Comment by lmparppei** [comment]
> Question: Did you change anything to the index lookup lately? Because if not, it feels odd that this should happen now when it hasn't before...

AFAIK not, but everything is possible. I've changed and optimized stuff here and there, but I'm unsure which of those changes could have caused this.

While I'm finding out what's going on, here's a bit cleaner way of doing what you're doing:

```javascript
Beat.onTextChange(function (location, length) { 
	if (location > 0) {
		let line = Beat.currentParser.lineAtIndex(location)
		if (line?.isOutlineElement()) return
	}
}
```

**Comment by ftolsson** [comment]
`.isOutlineElement()`, no less! 
I'll be damned, I need to start reading the wiki for additions more often! :)

**Comment by lmparppei** [comment]
(Not sure if it's mentioned in the Wiki, but I'll add it)

**Comment by ftolsson** [comment]
Some more information to potentially help sort this one out...:

I just had a crash checking a custom style for printing.
Here's the crash report:
[Beat-2022-08-07-152200.txt](https://github.com/lmparppei/Beat/files/9276875/Beat-2022-08-07-152200.txt)

Immediately after restarting Beat, FTOutliner constantly causes this again:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/25481285/183293168-042811d7-aa1d-42f1-9a21-8813e956993d.png">

Needless to say, it worked perfectly before the crash. Adding a scene or making other changes hoping to force Beat to get the `lineAtIndex()` method up and running doesn't help. Nor does restarting Beat (or FTOutliner).

Also, weirdly, after the crash Beat seems not to capitalize forced scene headings `.some scene` anymore -- and that also reamins after a restart.

This all seems very weird to me -- can you make anything out of it?

**Comment by ftolsson** [comment]
Okay: So I can reproduce the crash:

- Open the Print dialog.
- Check one custom style.
- While the preview is still redrawing, check another one.
- Crash.

My guess is that Beat tries to update the Preview with the new stylesheet, but can't find the Preview since it is away being redrawn. Probably some guard clause missing. 

But! Before you do -- if you force the same crash, do yo too experience `lineAtIndex()` returning null after restarting Beat?

**Comment by ftolsson** [comment]
And some further info:

For whatever reason, after forcing that crash the second time, Beat did not automatically open the top document (the one I was working in when preview/styles crashed Beat).
When I then went on to *manually* open my document, `lineAtIndex()` behaved fine, and scene headings capitalized correctly again! 

So... Might it be that after auto-reopening a document (after a crash?), Beat somehow does something differently...? 

BTW, this is all with Hide Fountain Formatting set to ON, in case that makes a difference.

**Comment by lmparppei** [comment]
This was a good old memory leak, and it's a surprise it didn't cause any errors prior to this. The virtual print view was stored in a single variable, ran in background and when a new preview was created, the reference disappeared and the orphaned class still tried to report that it finished the preview to print dialog.

However, I couldn't reproduce the other bug. I'm suspecting something isn't initialized the same way when recovering the document. By your description, it appears that while things might be rendered correctly, parser is somehow out of sync.

There could be something in your document that Beat parses incorrectly in some cases.

**Comment by lmparppei** [comment]
I will add `Beat.crash()`  to the plugin API. You could try causing a crash whenever the method returns a `null` and then paste the call stack, let's see if it gives us any more insight.

**Comment by ftolsson** [comment]
Clever! Will do!

**Comment by lmparppei** [comment]
I'm pretty sure this was resolved after adding more thread safety, or has it happened again?

**Comment by ftolsson** [comment]
Totally! I was just about to write that here but forgot about it. Close, close, close!
