### ISSUE TITLE
Escaped character, when not immediately preceded by blank line, prints WITH the backslash

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#122]
So -- I wanted to do a bullet-type list in italics.
I can think of two methods, either: 

```
\* *item one*
\* *item two*
\* *item three*
```

or

```
* \* item one*
* \* item two*
* \* item three*
```

However, both versions produce this:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/25481285/182832927-7de93f74-b0d2-4275-a1d9-6e8b51ff844f.png">

if adding a blank line between the lines though, each first backslash after a blank line will hide as expected.

This also applies to multiple escaped characters on the same line. 
Compare these two screenshots, where the blank line before the stars is the only difference:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/25481285/182834805-fa0940c6-0cfe-4a30-9584-29a5e183b2d7.png">
<img width="535" alt="image" src="https://user-images.githubusercontent.com/25481285/182834869-056437ef-329b-4f37-8564-b6d7692a9d59.png">

**Comment by lmparppei** [comment]
Thank you, fixed in `1.95.4`
