### ISSUE TITLE
Suggestion: Expand Fountain syntax with !! for shots

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#126]
This is a proposition that would probably be best directed at the creators of the Fountain language, but sadly there is no contact information on the fountain.io website, and their GitHub page has unanswered questions from years back.

Therefore, I propose this as a local extension of the Fountain syntax inside Beat, in hopes that the language may evolve as a result of usage.
 
#### PROBLEM:
With no dedicated SHOT element format in Fountain, entering a shot or sub-header can arguably only be done in one of two way:
1. As action, but styled manually (all caps, choice of bold). Done this way, shot lines risk being the last line of a page, counter to screenplay standards.
2. As a scene heading, forced by adding a period at the top of the line. This will solve the last-line-of-page issue, but instead the shot will be interpreted as a SCENE for purposes of numbering, presence in outlines, and not least when exporting to other apps (including scheduling software). This presents a bunch of other problems and will take a lot of cleaning up.

#### PROPOSITION:
Interpret double leading exclamation mark as SHOT/SUB-HEADER.

#### SAMPLE SYNTAX:
```
He walks up to the kitchen cabinets. Slowly opens one of them, and RECOILS:

!!INSIDE THE CUPBOARD

dozens of rats are scavenging among the age-old boxes of food.
```

#### PARSING/STYLING RULES:
* Will be converted into all caps (if not typed so already)
* May optionally be set in app to bold, underline or two lines before
* Most importantly: _will not print last on page_ but, when parsed for pagination, keep together with next element

#### EXPORT RULES:
Most apps (and most importantly Final Draft FDX) have a built-in, default format for shots. So any !! shot lines should export as such.

#### BACKWARDS COMPATABILITY:
For apps not parsing !! as shots, shot lines will print/display as an action line with a leading exclamation mark.
While not ideal, this will not break readability, and while waiting for adaption will cause the only a cosmetic, non-fatal, error (just as was probably the case in 2014 when ! @ and ~ was introduced in Fountain 1.1). 

For your consideration!

**Comment by lmparppei** [comment]
One of the original creators of Fountain is actually present on the Discord. We *could* try to open up a wider discussion about this, because it's an interesting question, one which I've stumbled upon myself, too.

I'm still a bit hesitant to add Fountain features that aren't somehow supported by other apps. I did it with strikethrough, but walked back after realizing the confusion it could create.

Let's discuss this further.

**Comment by ftolsson** [comment]
Oh, really? Introductions, please! 😊 

I had actually prepared this suggestion for the Fountain website (hence its formal nature) but realized too late that it is a one-way communication platform only.

I would love to discuss it further — I love the idea of Fountain — but the SHOT format is really missing for all the aforementioned reasons...

**Comment by ftolsson** [comment]
So, here goes!

### Some proposed "RULES" for a SHOT format:
 
#### Line has to meet three criteria:
* starts with `!!`
* previous line is empty
* next line is empty

_No automatic detection, only explicitly forced lines become shots._

#### Behavior & Format:
* Line is displayed in all caps (preserving lowercase behind-the-scenes, and reverting if the second ! is removed)
* Line may not display at bottom of page (or with only empty lines below it until bottom of page) but will then wrap onto next
* Otherwise takes on width and margins of action

#### Ideal implementation:
* Via settings, option to have shots automatically become BOLD
* Via settings, option to have shots get 2 empty lines before
* Disable automatically forced initial uppercase letter for action line directly following SHOT

#### Discussion:

Reasons for selecting `!!` as format code:
* As a neighboring, "superior" format to action, there is arguably a certain logic to forcing SHOTS with "more of the same" 
* While shots _might_ also be considered a lower-lever neighboring format to scene headings, two periods would potentially create confusion with lines starting with ellipsis ("...and THEN:") which all too many people type with two periods only. 
* but also, if incorrectly parsed by some other app that doesn't support shots, a line with two periods may be interpreted as intentional hesitation or concatenation, whereas two exclamation marks are a more obvious mistake
* There are of course other rarely-used symbols, but narrowing down the set of control characters to the ones already used will make the format much less daunting and tech-y.

**Comment by lmparppei** [comment]
The dual-markup character turns out to be a bit tricky parser-wise, but the prototype is kind of working now.

![image](https://user-images.githubusercontent.com/20226704/198268338-6c4b1789-e8a9-413d-9f25-4beef2227266.png)

**Comment by lmparppei** [comment]
(Implemented a while back)
