### ISSUE TITLE
Current dev build: toggleFullScreen does't exit full screen properly yet

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#129]
So -- the `.toggleFullScreen()` works great to make FTOutliner full screen! Cool! 

However, if then triggering `.toggleFullScreen()` again, the window will not exit screen.
*Something* happens though, bc the green traffic light button will now be greyed out.
The only way to really exit full screen mode for FTOutliner at this point is by closing it with the red traffic light button.

Also interestingly, about the green traffic light button:
* Before triggering `.toggleFullScreen()`, the green button will have a `+` icon when hovered
* After triggering `toggleFullScreen()`, it will have a "diagonal triangles" (fullscreen) icon.
* You CAN exit fullscreen properly if using the green button
* And if you do, the green button will from now on have the fullscreen icon rather than the plus icon, even when in non-fullscreen.

I'm thinking, besides making `.toggleFullScreen()` exit properly, could the green button be made to include fullscreen as an option even before the first trigger? Or is this a limitation in the OS?

**Comment by lmparppei** [comment]
Fixed in `1.98.1`, resubmitting now
