### ISSUE TITLE
Suggestion: Add keyboard shortcut to toggle case

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#132]
Toggle between UPPERCASE and lowercase is pretty common in screenwriting, especially when dealing with SOUND EFFECTS, characters' FIRST APPEARANCES, and sometimes important CAMERA DIRECTIONS that should be in UPPERCASE.

Found in other programs...
- **Final Draft:** Under the Format menu as "tOGGLE cASE"
- **Highland:** Under the Edit menu, submenu Transformations, as "Make uppercase" with the keyboard shortcut: Control+U
- **Fade In:** Under Format menu as "Upper/Lower Case" with the keyboard shortcut: Command+K

Suggested implementation...
- Under Format menu, right beneath Underlined, "Upper/Lower Case" with keyboard shortcut: Control+K
- Selected text changes lowercase to UPPER, UPPERCASE to lower

**Comment by lmparppei** [comment]
Added in 1.99.96:
- ^⌘U – make uppercase
- ^⌘L – make lowercase
