### ISSUE TITLE
Bug: App crashes on forcing elements

### ISSUE THREAD

**Issue by fufune** [lmparppei/Beat#133]
Bug:
The app continuously crashes every time you force elements like characters using "@" or Headings using "."

System:
On Mac os Ventura 13.4 , Macbook pro M1 pro. 

Beat App 1.98.4 beta.

PS: Fix to the issue is by downgrading to Beat app 1.98.1

**Comment by lmparppei** [comment]
The latest version is Beat **1.99.58**. You should update your app via App Store. These issues can't be reproduced in the latest builds.
