### ISSUE TITLE
Bug: Index Card view error

### ISSUE THREAD

**Issue by venkatgoud** [lmparppei/Beat#134]
Just installed, opened it and clicked on tutorial and got this error/warning.

I am on a very old Mac 10.14.6
<img width="474" alt="beat_warning" src="https://github.com/lmparppei/Beat/assets/4821174/444bc5cf-d2bd-4144-a74d-283df4530ec5">

**Comment by lmparppei** [comment]
Hmm. I think index cards are not compatible with macOS 10.14, because it has a very old version of WebKit. The card view probably needs to be disabled for older Macs. Does the app work otherwise?

**Comment by venkatgoud** [comment]
I have not imported larger scripts or unicode scripts yet but the app works fine so far.

**Comment by lmparppei** [comment]
I'm keeping the issue open, as you shouldn't see an error message. There should rather be some sort of message like "Index Cards are not supported in 10.14" in the card view on older computers.

**Comment by lmparppei** [comment]
@venkatgoud Let me know if this build fixes it for you:
https://www.dropbox.com/s/uj7x4ttjcg7e2vp/Beat%201.996.2.dmg?dl=1

**Comment by lmparppei** [comment]
Maybe NOW:
https://www.dropbox.com/s/uj7x4ttjcg7e2vp/Beat%201.996.2.dmg?dl=1

**Comment by venkatgoud** [comment]
No. Same issue.

**Comment by lmparppei** [comment]
This is now fixed in 1.996.4
