### ISSUE TITLE
Bug: If you highlight text and drag the cursor to far it will move away from the screenplay.

### ISSUE THREAD

**Issue by KingTheD** [lmparppei/Beat#143]
**Describe the bug**
If you highlight some text and drag your cursor all the way to the edge of the application window the text will move the opposite direction. 

**Screenshots**
<img width="1315" alt="Screenshot 2023-11-28 at 7 03 06 PM" src="https://github.com/lmparppei/Beat/assets/147949431/64e9de55-e94d-4e60-b02c-61f4162666d0">

**macOS version**
MacOS Ventura 13.6

**Comment by lmparppei** [comment]
Does the length of the document matter? I can't reproduce this myself.
