### ISSUE TITLE
Double-return press after dialogue does not assume "action" or "slug"

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#15]
Writing dialogue and hitting CR twice does not cause cursor to be placed for non-dialogue element (meaning: normally what's next after a double blank line will always be **action** or **slug**). 

Cursor remains in place until a non-CR key is pressed.

**Comment by lmparppei** [comment]
The reason is that the parser is parsing whatever you are inserting. This isn't ideal, but saves from many other troubles for now.

**Comment by lmparppei** [comment]
Fixed by parsing the cursor position.
