### ISSUE TITLE
Cannot turn off dark mode

### ISSUE THREAD

**Issue by keith105** [lmparppei/Beat#151]
After upgrading to the latest version of Beat, my script was shown in dark mode, even though I never enabled it. I cannot turn it off. I try to, but it refuses to switch it. I can change all of the other options (e.g. to show page numbering, etc).

**Comment by lmparppei** [comment]
Whoops. Fixed in 1.999.12, I'll submit a patch right away.

**Comment by keith105** [comment]
Thank you! Works great!
