### ISSUE TITLE
Two finger trackpad page scrolling freezes up with latest version

### ISSUE THREAD

**Issue by keith105** [lmparppei/Beat#154]
After saving an edit to my script, I try to use two fingers on the trackpad to scroll the page up and down, but it's frozen. The only way I seem to be able to fix this is by moving the cursor up or down using up/down buttons until the page starts scrolling, then the two finger scrolling works again.

**Comment by lmparppei** [comment]
I just got another report about this elsewhere. Could you add these:
- macOS version
- computer model

**Comment by lmparppei** [comment]
Also, does this build fix anything?
https://www.dropbox.com/s/uux4acrzpa3jwgo/Beat%201.999.18.dmg?dl=0

**Comment by keith105** [comment]
MacOS Sonoma 14.5. MacBook Air 13″.

**Comment by keith105** [comment]
Looks like that build fixes it!
