### ISSUE TITLE
Text within a parenthetical is auto-capitalized

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#16]
Parentheticals are auto-capitalized. Would be nice to turn this off.

**Comment by lmparppei** [comment]
Can you provide an example? They shouldn't be.

![image](https://user-images.githubusercontent.com/20226704/53650537-71266200-3c4d-11e9-80aa-8235ef69f2a4.png)

**Comment by darthrootbeer** [comment]
Figured it out. By default, I have these enabled:

- Edit > Spelling and Grammar > Check Spelling While Typing
- Edit > Spelling and Grammar > Correct Spelling Automatically

Which results in:

![screen shot 2019-03-01 at 11 33 06 am](https://user-images.githubusercontent.com/3142193/53651972-ce062600-3c15-11e9-84c2-2c422f5f46c9.png)
