### ISSUE TITLE
Feature Request: Make spell check optional

### ISSUE THREAD

**Issue by MiltonAkash** [lmparppei/Beat#160]
I'm from India. We used to write our regional language dialogues using english script. Works fine with other apps. but here we are seeing red squiggly lines everywhere due to this. Will be better if it is done. If possible spell check can be optional to action lines and paranthesis

**Comment by lmparppei** [comment]
Yes, I'm struggling with this myself as written and spoken Finnish are very different languages, so macOS thinks my dialogue is full of spelling errors.

I've tried to find a way to disable spell check for certain line types, but the system-wide spell checker isn't very friendly about this. I'll keep on looking!

**Comment by lmparppei** [comment]
<img width="535" alt="image" src="https://github.com/user-attachments/assets/69f3461c-b162-4123-907b-696bfbcfde76">
Well this was easy. It will be included in next version, under spell checking settings.
