### ISSUE TITLE
[Feature Request] Page view vs. full-window view

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#21]
Use a "page" view vs. full-window view. Meaning, you can see the defined left and right edges of the writing area. Left and right "margin" are different colors or at least visible. 

See screenshot.

![003 - background-color](https://user-images.githubusercontent.com/3142193/53643945-65ae4900-3c03-11e9-81d2-ded7bfa52363.jpg)

**Comment by lmparppei** [comment]
This is WIP.  Some issues and graphical glitches, so hasn't beed added to the main branch.

**Comment by lmparppei** [comment]
Implemented in 1.1.0i, though buggy. Graphicla glitches are now fixed in codebase, and will be available within next release.
