### ISSUE TITLE
[Feature Request] Custom CSS for all elements

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#27]
Custom CSS for all elements (this could roll up pretty much all of these others, below).

If you don't want to clutter your menus or add a Preferences panel, you could have Beat look for a custom CSS file in a default folder and apply that. CustomLight.css CustomDark.css, perhaps. Sample CSS XML file with elements labeled would be necessary.

Related:
#18 
#19 
#20 
#22 
#23 
#24 
#25

**Comment by lmparppei** [comment]
Well. Beat is suppose to be as minimalist as possible, and I don't want to complicate the code while I'm the only person responsible for it. My coding "skills" have already caused some weird bugs here and there, and custom styling would be a pretty easy way of allowing the user to break the whole app if they or the coder don't know what they're doing.

This might be a future milestone.

**Comment by darthrootbeer** [comment]
Totally understood. I currently use the free Highland 2, and have successfully hacked the styling to make custom colors. But this all gets broken when there's an update. Just a dream feature of mine. Can't complain, Beat works very well so far!
