### ISSUE TITLE
[Feature Request] Hide the "toggle outline" button

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#28]
Hide the "toggle outline" button (either completely, or unless the cursor is near it) for a more minimal experience.

**Comment by lmparppei** [comment]
I had planned that it would only show up on mouse move. The document window already recognizes mouse movement, but this will be added later on.

**Comment by lmparppei** [comment]
There's even more clutter on the screen right now, with the card view button. Couldn't really figure out how to register mouse movement or use timers, but maybe some day!

**Comment by lmparppei** [comment]
Done in 1.1.0i/h.
