### ISSUE TITLE
[Feature Request] Focus mode

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#29]
"Focus mode" - where only the current line (single line), sentence (start > end) or entire element are the standard text color; other elements are less opaque (amount of "dim" could also be set).

From Scrivener, three examples:

### Line
![image](https://user-images.githubusercontent.com/3142193/53644427-95118580-3c04-11e9-87c1-14254f3d5354.png)

### Sentence
![image](https://user-images.githubusercontent.com/3142193/53644451-a490ce80-3c04-11e9-9fa4-efe2b7ac6cab.png)

### Paragraph
![image](https://user-images.githubusercontent.com/3142193/53644478-b1152700-3c04-11e9-88e9-2ce542199e90.png)

**Comment by lmparppei** [comment]
Maybe some day.

**Comment by darthrootbeer** [comment]
Certainly a premium feature .. Not high priority. Thank you!
