### ISSUE TITLE
[Feature Request] Limit the minimum vertical window size 

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#30]
Limit the minimum vertical window size (instead of allowing user to shrink it all the way to the title bar). Or: Allow complete resizing of entire window.

![image](https://user-images.githubusercontent.com/3142193/53644605-f9344980-3c04-11e9-9f6d-82109fcb03e4.png)

**Comment by lmparppei** [comment]
Fixed in 1.0.5
