### ISSUE TITLE
[Feature Request] Allow for zoom in/out in Toggle Preview mode.

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#32]
Allow for zoom in/out in Toggle Preview mode. 

This is a lazy request, yes. User could export a PDF to macOS Preview and zoom/out themselves ... but it feels like it should be there. (Command - or Command + on a preview).

**Comment by lmparppei** [comment]
The toggle preview is a fixed-width WebKit window. It's more of an "extra" feature at this point and really only shows the default Fountain HTML version.

The Fountain to HTML objective C file is pretty self-explanatory and it's based on CSS, so if somebody is up to the task, fixing it should be easy.

**Comment by darthrootbeer** [comment]
Thanks. I don't know enough about the code to attempt, and it's a minor feature.

**Comment by lmparppei** [comment]
And version 1.0.6 now includes a full-screen preview with real pagination. I will add zoom in/out buttons when I have the time :-)

**Comment by lmparppei** [comment]
I guess this is irrelevant by now, as the preview follows the current scene + is more appropriately scaled from the start.
