### ISSUE TITLE
[Feature Request] Allow for auto-adjust to night mode vs. light mode based on macOS current mode

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#34]
Some people seem to like an option to "Match the mode of macOS" -- if we're in Mojave dark mode, go dark automatically. If we're in light, go light automatically.

**Comment by lmparppei** [comment]
It's already kind of implemented in the code, but I'm doing this on XCode 8 (for certain compatibility reasons), so it has to wait for now.
