### ISSUE TITLE
The first page shouldn't be numbered.

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#38]
Just wanted to point out that having the first page numbered goes against proper screenwriting format. In addition, it is unnecessary to number the first page of something. And I was wondering if you'd consider changing it. 

P.S. I love the program! It feels similar to Slugline, which is AWESOME! Look forward to the next update.

**Comment by lmparppei** [comment]
Fair enough and good point - this isn't so strict in Finland, so back when I rewrote the export, I decided to leave the first page numbered. I'll change it in the next patch.

**Comment by lmparppei** [comment]
Fixed, will be released in 1.7b.
