### ISSUE TITLE
[Feature Request] Name Database

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#39]
I wanted to suggest adding a feature from [Trelby](https://www.trelby.org/), a program that has sadly gone out of development.

In that program, the Name Database was always such a cool feature to have. And I used to use it almost every day. Now, I use [BehindTheName](https://www.behindthename.com/), which is good but just not the same. The ability to search by name origin, the starting letter, and gender was so very helpful in finding just the right character name for my story.

Implementing this feature wouldn't be too much work as the name database is a simple plain-text file: [Trelby's Awesome Name List](https://github.com/oskusalerma/trelby/blob/master/names.txt).

If you are interested in adding it, please let me know! Keep up the great work!

![trelby](https://user-images.githubusercontent.com/1820674/104357496-e3fff580-54d2-11eb-9b7d-c05737642436.png)

**Comment by lmparppei** [comment]
I guess I won't be adding this sort of stuff in the main app, but this could easily be implemented as a plugin. It might require some minor tweaking to the plugin API, though, as it doesn't support external files / libraries right now, or maybe somehow packing the name file into a single JavaScript file. Also, to consider my own inclusivity guidelines, the binary female/male terminology should be changed before bringing this to Beat.

Thanks for the suggestion, I'll look into bundling plugins with external files!

**Comment by lmparppei** [comment]
I made some evening tea and implemented external asset support for plugins. It allows plugins like this to be created.

**Comment by lmparppei** [comment]
![image](https://user-images.githubusercontent.com/20226704/104445436-c8175500-55a1-11eb-9cfa-3c42f26a8710.png)

The plugin API is now able to support this kind of plugin, and I wrote a quick & dirty version. I'll release the current code under GPL and make a separate repo so somebody with the time and skills can polish and optimize the code. Thanks for the suggestion!

**Comment by lmparppei** [comment]
The plugin code is here. Not that this won't work in the latest release, you'll need to wait for the 1.7b patch to use or further develop it. 

https://github.com/lmparppei/Character-Name-Database-Plugin-for-Beat

**Comment by harp37** [comment]
Wow, that was fast! Thanks so much for working on this!
