### ISSUE TITLE
Right margin too large on load

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#4]
When loading a fountain file, the right margin is too large, giving an "unbalanced" feel. This adjusts as soon as you resize the window. See screenshot.

![004 - right margin on load](https://user-images.githubusercontent.com/3142193/53642872-bd978080-3c00-11e9-85e8-21e70acc88d9.png)

**Comment by lmparppei** [comment]
Fixed in 1.0.4
