### ISSUE TITLE
[Feature Request] Character Mapping Report Based on Appearances

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#40]
Okay, so, that title blows... but basically I want to have a map of the script showing where characters come in and out of the story. It can be used to see whether a character "disappears" throughout the script or should "appear" earlier in the story.

As where all my completely original ideas come from, stolen from another screenwriting program, here's how it looks in Trelby...
![report5](https://user-images.githubusercontent.com/1820674/104467107-9095b200-557b-11eb-8cc5-3b5e7152768a.png)

Alright, I know! I know! It's a pretty ugly graph thing, but at least it's interesting way to visualize a script, which I'm a huge fan of.

I'd prefer a color version of this. Maybe the user could choose the colors or they are randomly assigned. Guess that'd be question brought up to the user before creating a new report, huh? I dunno...

Plus, (V.O.), (O.S.), (O.C.), etc. should be combined into one entry instead of multiple, like Trelby.

Trelby's code for reference can be found [here](https://github.com/oskusalerma/trelby/blob/master/src/dialoguechart.py) and [here](https://github.com/oskusalerma/trelby/blob/master/src/reports.py). Note: It's in Python, the programming language for hackers, nerds and the faint of heart.

**Comment by lmparppei** [comment]
This won't be part of the main app either, and the plugin API should be  used for these kinds of features from now on.

It should be easy enough to implement in JavaScript, too. Just iterate through the scenes and create an array mapping the appearances. Then show the results with `Beat.htmlPanel(...)`.

See more: http://kapitan.fi/beat/plugins/documentation.html

**Comment by lmparppei** [comment]
And now that I'm thinking of it, some sort of Plugin Pack repo would probably be helpful. If enough people are interested in creating one, I'm glad to help with understanding the plugin system and scripting, but too busy to take it on myself right now. 

Here's some code to get anyone started with this. It results with an object with the character names (key) and an array with scenes they have dialogue in (value).

````
let scenesForCharacter = {}
let index = 0

for (const scene of Beat.scenes()) {
    const lines = Beat.linesForScene(scene)
    let charactersInScene = [];

    for (const line of lines) {
        // Do (V.O.) etc. cleanup here
        if (line.typeAsString() == "Character") {
            let name = line.string
            if (!scenesForCharacter[name]) scenesForCharacter[name] = []
            if (!scenesForCharacter[name].includes(index)) scenesForCharacter[name].push(index)
        }
    }
    
    index++
}

Beat.alert("Scenes", JSON.stringify(scenesForCharacter))

````

**Comment by lmparppei** [comment]
![image](https://user-images.githubusercontent.com/20226704/105520270-256a7f00-5ce3-11eb-8707-459314fd4831.png)

This was kind of trivial to write, though it polishing it will be a much bigger task. I'll provide the code some time in the future. I'll also set up a plugin development repo.

**Comment by harp37** [comment]
Wow, that looks amazing! Thanks so much for doing this! I look forward to trying it out. :)

**Comment by lmparppei** [comment]
Here's a somewhat working version for download and repurposing. It's also contained in the plugin pack available to buy through itch.io. I'll make them all open source ASAP – this is only a fundraising scheme to get some loose change (like 10 eur) for all the upcoming hosting costs.

https://www.dropbox.com/s/ok52rc3cnghuctz/Map%20Character%20Appearances.beatPlugin.zip?dl=0

**Comment by lmparppei** [comment]
For anyone else reading this, public plugin development repository is now available here:  
https://github.com/lmparppei/BeatPlugins
