### ISSUE TITLE
[Feature Request] User-Customized Color Theme

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#41]
I don't know if you'd be interested, but I'd love a viewing mode that features a light page background but a dark user interface. It is featured in Fade In, Scrivener, etc. and I prefer it over Mac's standard dark mode, which is frankly quite dark.

I think it'd interesting to call it "Goldilocks" mode or something like that. But calling it "Happy Medium" might be a bit more reasonable and easier for the average chump who comes across it to understand without thinking too hard about classic literary references.

**Comment by lmparppei** [comment]
There have been requests for being able to customize the colors. This has been against Beat's design philosophy but doable. For now it's low-priority, but adding a third "theme" is completely possible. 

It's actually possible to modify the existing colors yourself – go to the Beat package (right click in Finder, show package contents) and navigate to the `Resources` folder. `Themes.plist` contains the theme RGB values. If you come up with something, submit the modified plist file to me via e-mail and I'll look into adding a new theme when I can.

**Comment by lmparppei** [comment]
Some work related to this can now be found under `User Interface/Themes` in the Xcode project. The plist file has been restructured (third entry in the dictionary is the new model) and the user-made theme should be saved as a plist in the app support dir.
