### ISSUE TITLE
[Plugin Suggestion] Built-In Ambient Music Player

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#42]
I know! I know! This might be a tad extreme to request such a thing in an application that writes screenplays, not music.

But I would love, love, love a plugin that plays light, open-source music in the background as I type. Even crazier... I just had another idea... maybe the music could stop or start if you don't type anything for 10 seconds. It could be a fun way of saying: "GET BACK TO WORK, YOU LAZY IDIOT!"

I don't know if that'd be too distracting to most people. Probably. But I'd just love someone who has the ba**s to pull it off.

Also, typewriter sound effects would be awesome. [FocusWriter](https://gottcode.org/focuswriter/) has [pretty good ones](https://github.com/gottcode/focuswriter/tree/main/resources/sounds). If someone's interested in doing crazy sh** like this... LET ME KNOW!

**Comment by lmparppei** [comment]
This is actually possible from `1.86` onward. Plugin API now allows plugins to be retained in memory, run in background, and even intercept changes to the document. 

I've already written a simple sine wave synth that plays sounds on key presses. Coming up in the next release. (And please, use the App Store distribution, for now – ad hoc build is not updated at the moment.)

**Comment by harp37** [comment]
Shut the front door! This'll no longer be just a far-fetched dream... I can hardly freakin' wait!!!

Thanks so much for your continued dedication and hard work! It's greatly appreciated. I've using the new version on the Mac App Store and loving it.
