### ISSUE TITLE
When Importing a Final Draft Document, Script Analysis Gets a Wee Bit Wonky

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#45]
<img width="194" alt="Screen Shot 2021-01-14 at 11 23 00 AM" src="https://user-images.githubusercontent.com/1820674/104626058-12104180-565b-11eb-8c68-75aeb2b65ab4.png">
I know this is a first-class problem and all!

- (A) having Final Draft 11
- (B) exporting it to a free screenwriting application

_BUT REGARDLESS_ I think all the locations should either be Sentence Case or ALL CAPS.

**Comment by lmparppei** [comment]
FDX compatibility is one of the core features in Beat. Some writers outline their screenplays in Beat and deliver in FD, and some even collaborate using both Beat and Final Draft. So anyway something is wrong with FD stuff, it should be reported.

This one isn't related to FDX import however. The labels would get fixed after saving and reopening the document, and this has to do with the way Beat uses rendered/stored string values in the editor. And I haven't taken that into account with CSS.

Anyway, this is now fixed and will be included in 1.7b patch.
