### ISSUE TITLE
Beat performance & memory consumption

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#46]
I'd love to have an Apple silicon native version. What can I do to make this happen?

**Comment by lmparppei** [comment]
I don't own a Mac with M1 chip for now, so I can't test it thoroughly, but AFAIK Beat should be compiled into a universal binary. I'm not sure about Sparkle framework, though – it might be still Intel-only. I'll have to check it when I can.

Still, Beat uses so little CPU and memory that the performance should not be really affected using Rosetta.

**Comment by harp37** [comment]
I'd be happy to maintain a universal binary. For a complete noob like myself, are there good resources/videos for getting started with Swift/Sparkle?

Also, here's a quick comparison with the same screenplay open under light use. Not scientific or anything, but it's still something...
<img width="948" alt="Screen Shot 2021-01-19 at 12 56 07 PM" src="https://user-images.githubusercontent.com/1820674/105080130-04d9c500-5a56-11eb-9c5d-eda6fe59d853.png">
<img width="897" alt="Screen Shot 2021-01-19 at 12 57 10 PM" src="https://user-images.githubusercontent.com/1820674/105080176-0d320000-5a56-11eb-9c80-b5204ea60fec.png">
<img width="900" alt="Screen Shot 2021-01-19 at 12 56 40 PM" src="https://user-images.githubusercontent.com/1820674/105080162-0b683c80-5a56-11eb-80f1-329d95608364.png">

**Comment by lmparppei** [comment]
Wow, that's actually a surprisingly big memory footprint. I get about 100MB on my MacBook. I'll have to check what's causing it. 

Because Beat is a non-profit app and coded by a non-programmer (me), there are some very known optimization issues here and there, which I'm working on when I can pinpoint and recognize them. Some WebView silliness appears to take up a lot of memory, and that should be easy enough to fix.

**Comment by lmparppei** [comment]
Apparently live pagination is the bottleneck, as I've suspected. 1.7b will have some optimization to the memory use by moving UI stuff into separate classes. Preview creation takes a lot of CPU too.

Live pagination performance could be **significantly** improved by allowing pagination to happen from a given index. That stuff is actually kind of written into the pagination class, and it already marks certain lines as safe starting points for pagination. I just haven't really implemented it yet.

`FountainPaginator` is the probably the messiest class in the whole app. Its logic is somewhat based on the old open source Fountain stuff, but 90% is rewritten for Beat. `livePaginationFor:(NSArray*)script fromIndex:(index)` has commented code which finds the safe line and page in which where to begin the calculation.

**Comment by lmparppei** [comment]
Sparkle Framework has now been updated with the latest version.

**Comment by harp37** [comment]
Beat now uses significantly less RAM on my MacBook Air M1: **144 MB**. Tested on 1.7.4b. However, I wish it could beat out (no pun intended) Final Draft in power, ram, and CPU usage. However, Final Draft still uses less (though it does feel slower than Beat for normal typing), and Highland feels by the far the fastest (no delays or freeze-ups whatsoever).

**Comment by lmparppei** [comment]
Thanks! Memory usage here is somewhat misleading. Beat seems to reserve more memory, but actually uses somewhat less memory than Final Draft. When you move to index card view, memory use drops like 90 Mb, so apparently most of RAM is taken up by the graphical UI. 

Still, Beat this is free and open software and I am not a programmer, so it's kind of a miracle that it's even *this* optimized. :-) Let's hope that some day a real engineer joins the team.

**Comment by lmparppei** [comment]
I found some apparent bottlenecks in the code and removed them, so many performance issues should be fixed now in 1.8.

I will open this issue to discuss further memory, CPU and energy consumption peaks and problems.

**Comment by harp37** [comment]
After installing 1.8, here's what I got...

<img width="922" alt="Screen Shot 2021-03-29 at 6 41 21 PM" src="https://user-images.githubusercontent.com/1820674/112913065-913fde00-90be-11eb-8d04-744bc00961bf.png">
<img width="918" alt="Screen Shot 2021-03-29 at 6 41 40 PM" src="https://user-images.githubusercontent.com/1820674/112913072-96049200-90be-11eb-9cf7-c989d8250002.png">

CPU: **6.3%**
RAM: **244.9 MB**

Not scientific or anything. Take it with a grain of salt.

**Comment by harp37** [comment]
**Updated Benchmarks**

_Program Version - RAM [average] / CPU [from idle to basic editing] running on M1 MacBook Air, base model_
**Beat 1.8.3** - 189.3 MB / 0.1 - 9.5 %
**Highland PRO 2.9.8.7279** - 99.5 MB / 0.0 - 11.6 %
**Final Draft 11** - 122.6 MB / 0.9 - 11.0 %
**Final Draft 12** - 238.8 MB / 0.7 - 16.1 %

**Comment by lmparppei** [comment]
Some long-running memory issues were fixed in the latest release (1.89.4). Memory consumption should be pretty constant and stabile now.
