### ISSUE TITLE
Icon to Match Big Sur Theme

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#48]
I came up with an icon to match Big Sur. It's not perfect, but at least it's similar to the original icon.
![NEW-ICON-SUGGESTION](https://user-images.githubusercontent.com/1820674/105380384-6f643f80-5bd3-11eb-8bfe-bb0baf27b3a9.png)

**Comment by lmparppei** [comment]
![image](https://user-images.githubusercontent.com/20226704/105489342-bfb6cc80-5cbb-11eb-947b-54b1fdbacecd.png)
Here's the official Big Sur icon, which I still haven't updated into the app, because I'm not too fond of the plainness of the "b". It'll probably be shipped with 1.7.2.

**Comment by lmparppei** [comment]
![image](https://user-images.githubusercontent.com/20226704/105499679-833e9d00-5cca-11eb-90ea-401f24eac90a.png)

(Well, it actually looks kind of nice on the dock, even though it's less playful than the original was.)
