### ISSUE TITLE
[Feature Request] User-Defined Editor Font

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#49]
I know, I know that it'll make the program more complicated! But at least for the editor font, not the page output, I think having some font options would be great.

Similar to Highland, only showing Courier fonts and select others, such as Helvetica, might be for the best practice to make it less complicated for the end user. It might also be good to add to the "Customize Colour/View" tool.

**Comment by lmparppei** [comment]
There was a vote about this earlier, and it was voted against. There is still a built-in option to use sans-serif version (similar to Highland), but it's unused and probably won't be implemented any time soon.
