### ISSUE TITLE
Cursor sticks to left on full screen for new file

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#5]
When switching to full screen in a new file, the cursor stays to the far left until you type.

**Comment by lmparppei** [comment]
This is a Cocoa graphical quirk. I don't know how to resolve this, but will look into it when possible.

**Comment by lmparppei** [comment]
Seems to be fixed no. No idea what I did, but it works. Duct-taped dreams, hopes and aspirations.
