### ISSUE TITLE
[Feature Request] Install Plugins Through The App Itself

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#51]
I really like the concept of a plugin library, where users can ONLY add the features they want. I think having this functionality will be a real advantage over using Final Draft, Fade In and, to some extent, Highland, which all suffer from the TRYING TO PLEASE EVERYONE AT ONCE mentality of modern software.

That being said, having a way to install these plugins easily would be BADASS. This'd be especially useful for the average user who won't be as tech savvy to install cool new add-ons to their favorite writing companion. 

Perhaps it could look like the App Store with screenshots of each plugin followed by a short title. Also, information within the "plugin library" on how and where to contribute new plugins would be ICING ON THE CAKE.

**Comment by lmparppei** [comment]
Yeah, at least some user-friendly way to manage the plugins should be available, even if it's just add/remove. 

I don't want to make the plugin stuff too public or visible for now, as the API is still in development, and I'm kind of regretting releasing it already. The latest app version even broke some of the plugin functionality as I was tracking memory issues, but I'm releasing a patch for it this weekend.

**Comment by lmparppei** [comment]
The plugin menu now has an item called "Open Plugin Folder", which makes installing plugins at least one step easier. Released in 1.7.2.

**Comment by lmparppei** [comment]
1.84 includes Plugin Manager, which allows the users to download and update official plugins from this repository.

**Comment by harp37** [comment]
Awesome! I'll give it a try.

**Comment by lmparppei** [comment]
It’s not public yet, will be published next week or so. 

--
Lauri-Matti Parppei
KAPITAN!
0405730823
www.kapitan.fi
