### ISSUE TITLE
Option to Use Big Sur's Native Accent Color.

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#59]
Using Final Draft 12 what surprised me the most, as silly as it might sound, was that selecting text finally uses the user-defined accent color in Big Sur, making it look much better than it did in FD 11. It got me thinking: **could there be an option to use the accent color defined by the user under Big Sur?**

**Comment by lmparppei** [comment]
Sorry for ignoring this – I haven't yet migrated to Big Sur on my personal machine because of some legacy software. This will be easy to implement once I get there. But which elements should *actually* have the accent color?

**Comment by lmparppei** [comment]
Implemented in `1.89.9`
