### ISSUE TITLE
Double-clicking in typewriter mode 

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#62]
Suggestion: Could clicking in typewriter mode listen for mouseup rather than mousedown, and preferably with a little delay before scrolling into place? 
Or probably better still: Allow inserting the caret anywhere without scrolling, and perform the scroll on a keypress. (This is arguably how most other apps with a typewriter mode do it)

As of now, clicking-to-select (or worse: double-clicking) anywhere but at the center of the screen will move the spot you're interacting with away from under your fingers which kind of makes you lose your bearings. Double-clicking a word even scrolls away so quickly that Beat selects the entire paragraph(s) that scroll by during the time of your double-click, rather than the single word you wanted to select.

**Comment by lmparppei** [comment]
Good point. Typewriter mode is now using `selectionDidChange` delegate event rather than keypresses. Should be easy enough to fix.

**Comment by lmparppei** [comment]
Fixed in `1.89.9`
