### ISSUE TITLE
Automatically select "US Letter" for US users

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#67]
It'd be great to have the software automatically detect whether it's a US user or not.

**Comment by lmparppei** [comment]
Probably doable by looking into the OS default when installing the app for the first time. It's a quick setting, though, and the rest of the world is living in complete harmony with standardized paper sizes, so, well. I'll leave this open and will look into it when I have the time.

**Comment by lmparppei** [comment]
Implemented in `1.90.4`
