### ISSUE TITLE
Action elements should be able to contain more than two carriage returns in series without having two spaces on each “blank” line.

### ISSUE THREAD

**Issue by BFLTP** [lmparppei/Beat#70]
According to the Fountain syntax, “Fountain respects your line-by-line decision to single or double-space, taking every carriage return as intentional” ([“Action”](https://fountain.io/syntax#section-action)), and “unlike some markup languages, Fountain takes every carriage return as intent” ([“Line Breaks”](https://fountain.io/syntax#section-br)). The language is ambiguous but is more consistent with all carriage returns/line breaks in action elements being rendered in the screenplay document.

Currently, Beat recognizes single and double spaces, as in
```
Is this your first time using Beat?
This file is a playground for you to mess around with.

In Beat, you don't need to press any special keys to write dialogue or a scene header.
```
but does not recognize triple or more spaces, as in
```
Is this your first time using Beat?


This file is a playground for you to mess around with.





In Beat, you don't need to press any special keys to write dialogue or a scene header.
```
unless there are two spaces in each blank line, as in
```
Is this your first time using Beat?
[[These blank lines each have two spaces.]]  
  
This file is a playground for you to mess around with.
  
  
  
  
  
In Beat, you don't need to press any special keys to write dialogue or a scene header.
```
(Also, that comment, `[[These blank lines each have two spaces.]]`, would not be recognized by Beat as a note.)

**Comment by lmparppei** [comment]
The note bug has been fixed in `1.90.4`, also triple spaces are now supported.

**Comment by BFLTP** [comment]
Some less ambiguous language from the bottom of the [“Action” section](https://fountain.io/syntax#section-action) that I failed to notice when I posted this issue: “Action also respects vertical whitespace. Any number of empty lines in the Fountain file will be passed faithfully through to the formatted output as empty Action lines.” But the Fountain interpreters Highland 2, [Afterwriting](https://afterwriting.com), and Beat’s Continuous Parser do seem inconsistent in how they process Action elements with multiple blank lines. Other Fountain interpreters might be similarly inconsistent.

I would personally favor being able to add multiple empty lines without having to force them because it would be slightly more efficient in making those stylistic decisions, and it would make the method of adding three or more carriage returns in a row the same as that of adding one or two—why should it be more difficult to create triple or more spaces than to create single and double spaces?

**Comment by lmparppei** [comment]
If somebody else reads this, I'll write some clarification about how line breaks are handled.

Beat is **not** a WYSIWYG editor, and neither are any other Fountain editors, so all line breaks can't be rendered into the final document as-is. Also, in the original Fountain export to HTML code, multiple empty lines are completely ignored. 

This is mostly a wise practice, because the following text:

```
EXT. YARD - DAY

A character does something.

# Second Act

INT. A SCENE - DAY

= This part needs some work

The same character does something else
```

Should not be rendered like this:
```
EXT. YARD - DAY

A character does something.


INT. A SCENE - DAY


The same character does something else
```

So, to make things easier, Beat just ignores empty lines altogether when exporting, and paragraph spacing replaces empty carriage returns in the final layout. Unless the line breaks are intentionally forced, it's safer to render paragraphs this way, so that no extra whitespace is generated.

However, I will do some tests to see how rendering intended line breaks **between action paragraphs** would affect the general experience. So, for example, this would be rendered as written:
```
INT. SCENE - DAY

An action paragraph.



Multiple line breaks between two actions.
```

**But** this would not:
```
INT. SCENE - DAY

An action paragraph.





EXT. ANOTHER SCENE - NIGHT

The line breaks before scene heading won't be rendered as whitespace.
```

**Comment by BFLTP** [comment]
> However, I will do some tests to see how rendering intended line breaks **between action paragraphs** would affect the general experience.

I like this idea a lot. I’m pretty sure that this is how line breaks are supposed to be handled anyway—empty lines within Action, which is “any *paragraph* that doesn’t meet criteria for another element.” So empty lines before and after Action elements, which begin and end with text, not line breaks, would be ignored, and empty lines within those Action elements would be rendered as they are within the plaintext.

**Comment by rnkn** [comment]
The stuff on the website about Fountain respecting all line breaks can pretty much be ignored. It's was a bad idea that no Fountain tools adhere to.

It's far more likely that people will accidentally leave extra unwanted blank lines in than it is someone wants those blank lines preserved (in which case, force the blank lines).

**Comment by lmparppei** [comment]
Agreed. My tests also suggested that it made things quite complicated and possibly difficult to understand for less experienced users. Those who want extra line breaks, probably know how to do them, and the new "empty" glyphs might also help.
