### ISSUE TITLE
Suggestion: Allow opening Beat with shift pressed as way to not restore previous session

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#73]
If Beat crashes on startup for whatever reason, it would be great to be able to rule out any active document as the culprit by starting Beat without restoring windows from last session.

It seems the Apple guide lines for this is to hold shift when opening: https://support.apple.com/en-us/HT204005

So if doable, this would be a helpful addition.

**Comment by lmparppei** [comment]
I tried implementing this, but for some reason, it doesn't work reliably. Consideration for the future.

**Comment by lmparppei** [comment]
Implemented in `1.91.8`
