### ISSUE TITLE
When turning on Show Outline, if the window width is equal to or greater than the desktop width minus the Outline sidebar width, the window is narrowed down to a certain standard width that may be narrower than the desktop

### ISSUE THREAD

**Issue by BFLTP** [lmparppei/Beat#76]
For example, if the window currently fills the desktop (which can be achieved by holding <kbd>Option</kbd> and double clicking any corner of a window, or in most applications holding <kbd>Option</kbd> and clicking the green window button) and the user turns on Show Outline, the width of the window actually gets reduced. I would like that Beat does not ever automatically reduce the size of the window when turning on this view option.

**Comment by lmparppei** [comment]
Fixed in `1.92.5`
