### ISSUE TITLE
Revert to Saved command breaks Live Preview

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#8]
Using "Revert to Saved" seems to break "Live Preview". See screenshot.

![001 - revert to saved](https://user-images.githubusercontent.com/3142193/53643231-8f667080-3c01-11e9-80fb-886667dab328.png)

**Comment by lmparppei** [comment]
Uhhh. This is kind of fixed, but sometimes copying and pasting stuff leads to messed up formatting. For the next version (1.0.7) I added "Reformat Everything" menu option, which does exactly what it says: reformats the whole script. It's sort of a panic button for these sorts of situations.
