### ISSUE TITLE
Recoloring scenes from outline adds increasing number of spaces

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#81]
Here's a simple one to fix for once! :)

This affects your own outline as well as my plugin when I use `Beat.setColorForScene`:

When adding the `[[COLOR: someValue]]` note to a scene heading, Beat adds a `[space]` between the heading text and the "note". 
When removing and/or changing the value, it doesn't remove the space before adding a new one, which results in scene headings that appear either with an increasingly loooong distance to the color note, or (if sceneheadings are underlined) a really long superfluous underline.

This is in the edit window only, so purely cosmetic. But still.

**Comment by lmparppei** [comment]
Can't reproduce myself, but added a check if there's already (at least) one space after the heading.
