### ISSUE TITLE
1.92.2 (and onwards?) API missing get...() for setDocumentSetting() and setRaw...Setting()

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#87]
Here's hoping you've laid all the groundwork already but just forgot to include two methods in the API...
...because right now, as far as I can tell, plugins can save stuff to the document (great!) but then... well, not read them again.

I actually peaked into your latest `BeatPluginParser.h` to see if perhaps you'd named the corresponding methods to something else, but to me it seems as if they're not there yet. (I did find a `getPropertyValue()` though — _for those who really know what they're doing_ — but I was obviously not one of them... :)

So. Keeping my fingers crossed that `getDocumentSettings()` and `getRawDocumentSettings()`are more or less done and won't take too much effort to connect to the API.

That's all!

**Comment by lmparppei** [comment]
This is what a quality-made enterprise software looks like.

Thank you, fixed in `1.923`

**Comment by ftolsson** [comment]
Not to add comments to a closed issue (or, well, I guess I am) but...
...am I doing this wrong?

<img width="372" alt="image" src="https://user-images.githubusercontent.com/25481285/146637273-f714494e-df96-48e7-8cb8-643a2298e3fd.png">

**Comment by ftolsson** [comment]
Oh. Wait. Because -- I am allowed to write my own settings, right...?
That's what I gathered from the announcement in discord, but from the wiki I'm not so sure anymore...

But it does seem like I'm allowed to save settings though -- with this code:
`Beat.setDocumentSetting("documentName", documentName)`
I get this in the Beat file:
`BEAT: {"FTOutliner: documentName":"Testing"  (...)`

It's just that I can't seem to retrieve that saved setting again...?

**Comment by lmparppei** [comment]
This is what world-famous Finnish minimalist design looks like. I've now *actually* exposed those methods to the API.
