### ISSUE TITLE
Toggling Live Preview off then on can cause crash for certain fountain files

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#9]
Toggling Live Preview off, then on, causes crash (see crash dump 002). Depends on the script.

[crash_dump_002.txt](https://github.com/lmparppei/Beat/files/2919725/crash_dump_002.txt)

**Comment by darthrootbeer** [comment]
Sample file to test.

[48 HRS [1982] [Fountain] [Spottiswoode, Hill].fountain.zip](https://github.com/lmparppei/Beat/files/2919726/48.HRS.1982.Fountain.Spottiswoode.Hill.fountain.zip)

**Comment by lmparppei** [comment]
I guess I will remove the option for live preview altogether. It seems to cause a lot of trouble. It's inherited from the original project (Writer) and haven't really used Beat while it's off.

**Comment by lmparppei** [comment]
Enabling and disabling live preview is removed for now.
