### ISSUE TITLE
Cosmetic only: If removing "mark for removal", red strikeout stays

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#91]
Basically what the subject says. If mistakenly marking for removal (instead of removing revision mark because obviously this user is unable to separate the shortcuts for those two) then trying to remove the "markings for removal" removes the red background but not the strikeout.

This is cosmetic only so does not affect print/export, but will stay until document is closed and reopened.

**Comment by lmparppei** [comment]
Fixed in `1.92.4`
