### ISSUE TITLE
Moving scenes in Index Card view no longer works

### ISSUE THREAD

**Issue by lmparppei** [lmparppei/Beat#94]
Something is up with dragging & dropping in Index Card view. I might have broken it couple of versions ago.

Here's the bug report from a user:

- When I drag and move a scene, I get the spinning indicator and the card move doesn't ever complete. Only solution is to press Escape key to exit card view. (when I move scenes via the outline view it happens instantly.)
- Sometimes a card will get 'stuck' to the mouse pointer, and a floating transparent card stays with the pointer. Clicking or double-clicking doesn't drop the floating card or make it go away. Again, I can press Escape key to exit card view.

**Comment by ockham** [comment]
This seems to have fixed per 5d134895524763723e31d89e0e39fcfdebda850c (v1.92.6), right? 🙂

**Comment by lmparppei** [comment]
Yep!
