### ISSUE TITLE
Nothing to lose sleep over, but htmlWindow.setTitle() is not connected?

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#98]
Working with several episodes in tabs, I just thought it would be helpful to display the current script title in the outline window title bar too. It's all really nice-to-have and far from need-to, so no big deal -- but wanted you to know since after all it's in the documentation:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/25481285/147739952-d6ba02a9-8a2d-43d7-a8f7-6ba9b43c04fa.png">

**Comment by lmparppei** [comment]
Weird, it is there but doesn't appear to be working. 
I'll remove the method from documentation, because  you can do the same using `window.title = "Hello"`

**Comment by ftolsson** [comment]
Oh, really! I thought that was read-only. Well, then TOTALLY nothing to lose sleep over.
